# Generated by Django 6.0.7 on 2026-08-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='Прізвище'),
            preserve_default=False,
        ),
    ]
