# Generated by Django 6.0.7 on 2026-09-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primal_training', '0002_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='description_cs',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='title_cs',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва класу'),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва класу'),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва класу'),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва класу'),
        ),
    ]
