# Generated by Django 6.0.7 on 2026-09-26 08:21

from django.db import migrations
from django.contrib.auth.hashers import make_password



def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='Dima').exists():
        User.objects.create(
            username='Dima',
            email='admin@example.com',
            password=make_password('12345678'),
            is_superuser=True,
            is_staff=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('primal_training', '0003_fitnessclass_description_cs_and_more'),
    ]

    operations = [
    ]
